[MODGOBI-132]-updated VendorDetails Mapping
folio-org/mod-gobi pull request #162
Opened 2022-04-27 07:57 UTC by SinghAdes

## Purpose

## Approach

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [x] Duplications on new code is 3% or less
  - [x] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [x] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2022-04-27 10:19 UTC, AndreiMPV requested changes

2022-04-27 10:19 UTC, AndreiMPV commented on src/main/java/org/folio/gobi/Mapper.java
> +          if (o != null) {
Please move lines 833 to 844 it to private method

2022-04-27 10:19 UTC, AndreiMPV commented on src/main/java/org/folio/gobi/Mapper.java
> +              if (!HelperUtils.extractSubAccount(organization.getAccounts().get(0).getAccountNo()).equals(vendorAccountfield.resolve(doc).join())) {
NPE can be possible organization.getAccounts().get(0).getAccountNo()

2022-04-27 10:19 UTC, AndreiMPV commented on src/main/java/org/folio/gobi/Mapper.java
> +              if (!HelperUtils.extractSubAccount(organization.getAccounts().get(0).getAccountNo()).equals(vendorAccountfield.resolve(doc).join())) {
Also don't include int equals complex logic lie vendorAccountfield.resolve(doc).join()
if it fail then will be difficult to understand a root cause

2022-04-29 08:50 UTC, AndreiMPV requested changes

2022-04-29 08:50 UTC, AndreiMPV commented on src/main/java/org/folio/gobi/Mapper.java
> +          .ifPresentOrElse(organizationAccountNo ->{
Organization can have or can't have account and line "organization.getAccounts().get(0)" in that case will throw NPE

2022-04-29 09:17 UTC, grabsefx commented
Please make this mapping configurable by adding lookup to the configuration files https://github.com/folio-org/mod-gobi/tree/master/src/main/resources

2022-04-29 14:25 UTC, SinghAdes commented
> Please make this mapping configurable by adding lookup to the configuration files https://github.com/folio-org/mod-gobi/tree/master/src/main/resources

@grabsefx :- I may not be sure about the flow but i think we are already doing a lookup here  :-
[https://github.com/folio-org/mod-gobi/pull/162/files/93fc2a88b5b394ab3831f17a177d67e74989f75a#:~:text=organization%20%3[…]ccountfield%20%2D%3E%20%7B](https://github.com/folio-org/mod-gobi/pull/162/files/93fc2a88b5b394ab3831f17a177d67e74989f75a#:~:text=organization%20%3D%20(Organization)%20o%3B-,Optional.ofNullable(mappings.get(Mapping.Field.VENDOR_ACCOUNT)),-.ifPresent(vendorAccountfield%20%2D%3E%20%7B)

i would be thankful if you can help me on this . thanks in advance.

2022-05-04 06:13 UTC, grabsefx approved these changes

2022-05-04 06:14 UTC, grabsefx commented
> > Please make this mapping configurable by adding lookup to the configuration files https://github.com/folio-org/mod-gobi/tree/master/src/main/resources
> 
> @grabsefx :- I may not be sure about the flow but i think we are already doing a lookup here :- [https://github.com/[/pull/162](https://github.com/folio-org/mod-gobi/pull/162)/files/93fc2a88b5b394ab3831f17a177d67e74989f75a#:~:text=organization%20%3[…]ccountfield%20%2D%3E%20%7B](https://github.com/folio-org/mod-gobi/pull/162/files/93fc2a88b5b394ab3831f17a177d67e74989f75a#:~:text=organization%20%3D%20(Organization)%20o%3B-,Optional.ofNullable(mappings.get(Mapping.Field.VENDOR_ACCOUNT)),-.ifPresent(vendorAccountfield%20%2D%3E%20%7B)
> 

ok. leave it as is then. approved

2022-05-04 08:51 UTC, AndreiMPV approved these changes

2022-05-04 08:55 UTC, merged